// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLktlLzuewOyrkNfjJiq1GvertdWHxjWo',
    appId: '1:356673985471:web:07565a83dc7ecd4ce2df0a',
    messagingSenderId: '356673985471',
    projectId: 'flutter-web-rtc-abda7',
    authDomain: 'flutter-web-rtc-abda7.firebaseapp.com',
    storageBucket: 'flutter-web-rtc-abda7.appspot.com',
    measurementId: 'G-3Q1DRPNGSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxGJynrcjiLkhIFnzDgJkfXaz1QWJhxvY',
    appId: '1:356673985471:android:ea1e4cbb521899a4e2df0a',
    messagingSenderId: '356673985471',
    projectId: 'flutter-web-rtc-abda7',
    storageBucket: 'flutter-web-rtc-abda7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3NFFHqOOS9ipOtXJcL7RNwkaqs0gYD0w',
    appId: '1:356673985471:ios:b013d1f5129d40e8e2df0a',
    messagingSenderId: '356673985471',
    projectId: 'flutter-web-rtc-abda7',
    storageBucket: 'flutter-web-rtc-abda7.appspot.com',
    iosBundleId: 'com.example.videoCallFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3NFFHqOOS9ipOtXJcL7RNwkaqs0gYD0w',
    appId: '1:356673985471:ios:4aeabacb52e9d83ce2df0a',
    messagingSenderId: '356673985471',
    projectId: 'flutter-web-rtc-abda7',
    storageBucket: 'flutter-web-rtc-abda7.appspot.com',
    iosBundleId: 'com.example.videoCallFlutter.RunnerTests',
  );
}
